FROM public.ecr.aws/bitnami/python:3.8
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1


WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /usr/src/app/
COPY ./entrypoint-dev.sh /usr/src/app/entrypoint-dev.sh
RUN chmod +x /usr/src/app/entrypoint-dev.sh
ENTRYPOINT ["/usr/src/app/entrypoint-dev.sh"]