FROM public.ecr.aws/bitnami/node:14.15.5

# make the 'app' folder the current working directory
WORKDIR /app/

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . /app/

#Set environment variables
ENV SENTRY_DISABLED=true

# expose port 3000 to the host
EXPOSE 3000

ENTRYPOINT [ "docker/start_dev.sh" ]
